services:

  spark-master:
    build: ./spark-image # Download prebuilt Spark machine
    user: root

    container_name: spark-master # "This container is the cluster manager"

    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
    
    environment:
      - SPARK_MODE=master

    ports:
      - "8085:8080"  # Spark Web UI
      - "7079:7077"  # Spark cluster connection
    
    volumes:
      - ./input:/input
      - spark-data:/data

  spark-worker-1:
    build: ./spark-image
    user: root

    container_name: spark-worker-1

    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077

    ports:
      - "8081:8081"  # Spark Worker Web UI

    depends_on:
      - spark-master

    volumes:
      - ./input:/input
      - spark-data:/data

  spark-worker-2:
    build: ./spark-image
    user: root

    container_name: spark-worker-2

    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
  
    ports:
      - "8082:8081"  # Spark Worker Web UI

    depends_on:
      - spark-master

    volumes:
      - ./input:/input
      - spark-data:/data

  jupyter:
    build: ./jupyter-image
    user: root

    container_name: jupyter

    ports:
      - "8888:8888"
      - "4040:4040"  # Spark application UI

    depends_on:
      - spark-master

    volumes:
      - ./input:/input
      - spark-data:/data

  minio:
    image: minio/minio # Small object storage server compatible with Amazon S3 APIs

    container_name: minio

    command: server /data --console-address ":9001"

    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123

    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # MinIO Console UI

    volumes:
      - minio-data:/data

  kafka:
    image: apache/kafka:3.7.0

    container_name: kafka

    ports:
      - "9092:9092"

    environment:
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

    volumes:
      - kafka-data:/bitnami/kafka

  
volumes:
  spark-data:
  minio-data:
  kafka-data: